version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_jdruwa
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${TZ}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8.12
    container_name: pgadmin_jdruwa
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      # PGADMIN_CONFIG_SERVER_MODE: "False"   # mode mono‑utilisateur pratique en dev
      TZ: ${TZ}
    ports:
      - "${PGADMIN_PORT}:80"
